# Generated by Django 6.1.1 on 2026-09-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Espacio de Trabajo',
                'verbose_name_plural': 'Espacios de Trabajo',
                'db_table_comment': 'Espacios de trabajo organizacionales que agrupan múltiples tableros y equipos.',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('color', models.CharField(default='#10b981', max_length=20, verbose_name='Color')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel de Urgencia')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'db_table_comment': 'Niveles de prioridad para categorizar la urgencia de cada tarjeta.',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='RolColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Rol de Colaborador',
                'verbose_name_plural': 'Roles de Colaboradores',
                'db_table_comment': 'Roles y niveles de permisos para miembros de espacios y tableros (ADMIN, MIEMBRO, OBSERVADOR).',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('cargo', models.CharField(default='Miembro del Equipo', max_length=80, verbose_name='Cargo / Rol')),
                ('color_avatar', models.CharField(default='#0284c7', max_length=20, verbose_name='Color')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table_comment': 'Registro de usuarios y perfiles que participan en los tableros de TaskFlow.',
            },
        ),
        migrations.CreateModel(
            name='VisibilidadTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Visibilidad de Tablero',
                'verbose_name_plural': 'Visibilidades de Tablero',
                'db_table_comment': 'Nivel de visibilidad y acceso de un tablero (privado, espacio, público).',
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color_fondo', models.CharField(default='#0284c7', max_length=30, verbose_name='Color de Fondo')),
                ('icono', models.CharField(default='📋', max_length=10, verbose_name='Ícono')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='taskflow_app.espaciotrabajo')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_creados', to='taskflow_app.usuario')),
                ('visibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskflow_app.visibilidadtablero')),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'db_table_comment': 'Tableros estilo Kanban para gestión visual de proyectos y tareas.',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posición / Orden')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='taskflow_app.tablero')),
            ],
            options={
                'verbose_name': 'Lista de Tablero',
                'verbose_name_plural': 'Listas de Tablero',
                'db_table_comment': 'Columnas o listas que representan las etapas del flujo de trabajo (Kanban).',
                'ordering': ['posicion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Color')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='taskflow_app.tablero')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table_comment': 'Etiquetas de color para clasificar tarjetas según temáticas o áreas.',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posición / Orden')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite / Vencimiento')),
                ('estimacion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimación en Horas')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='taskflow_app.lista')),
                ('prioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='taskflow_app.prioridad')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_asignadas', to='taskflow_app.usuario')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_creadas', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table_comment': 'Tarjetas de trabajo individuales con contenido, responsables y plazos.',
                'ordering': ['posicion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título de Checklist')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posición / Orden')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='taskflow_app.tarjeta')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'db_table_comment': 'Listas de comprobación o subtareas asociadas a una tarjeta.',
                'ordering': ['posicion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posición / Orden')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taskflow_app.checklist')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'db_table_comment': 'Elementos individuales o pasos verificables dentro de una checklist.',
                'ordering': ['posicion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle del Movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='taskflow_app.tablero')),
                ('tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='taskflow_app.tarjeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_registradas', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historiales de Actividades',
                'db_table_comment': 'Auditoría cronológica de eventos y cambios ocurridos en el tablero.',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='espaciotrabajo',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_creados', to='taskflow_app.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del Comentario')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='taskflow_app.tarjeta')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table_comment': 'Comentarios y retroalimentación de los usuarios en cada tarjeta.',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=200, verbose_name='Nombre del Archivo')),
                ('url_recurso', models.CharField(max_length=500, verbose_name='URL o Enlace del Recurso')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Archivo')),
                ('tamanio_kb', models.IntegerField(blank=True, null=True, verbose_name='Tamaño en KB')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='taskflow_app.tarjeta')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_subidos', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'db_table_comment': 'Archivos adjuntos, documentación y enlaces asociados a una tarjeta.',
            },
        ),
        migrations.CreateModel(
            name='TarjetaEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_asociadas', to='taskflow_app.etiqueta')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_etiquetas', to='taskflow_app.tarjeta')),
            ],
            options={
                'verbose_name': 'Etiqueta de Tarjeta',
                'verbose_name_plural': 'Etiquetas de Tarjetas',
                'db_table_comment': 'Relación de asignación entre tarjetas y etiquetas temáticas.',
                'unique_together': {('tarjeta', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='MiembroTablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskflow_app.rolcolaborador')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='taskflow_app.tablero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros_asignados', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Tablero',
                'verbose_name_plural': 'Miembros de Tablero',
                'db_table_comment': 'Colaboradores asignados específicamente a un tablero.',
                'unique_together': {('tablero', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='MiembroEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='taskflow_app.espaciotrabajo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskflow_app.rolcolaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_espacios', to='taskflow_app.usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Espacio',
                'verbose_name_plural': 'Miembros de Espacio',
                'db_table_comment': 'Asignación de usuarios a espacios de trabajo con un rol determinado.',
                'unique_together': {('espacio', 'usuario')},
            },
        ),
    ]
